### ISSUE TITLE
SEQUELstats.sh: line 111: bsub: command not found

### ISSUE THREAD

**Issue by splaisan** [VertebrateResequencing/SEQUELstats#1]
Your readme says:

> _While the `SEQUELstats.sh` script makes use of **IBM Platform LSF Standard 9.1.3.0** for parallel processing of BAM files, the actual pipeline will run on any machine fulfilling the above-mentioned requirements. Hence, it is possible to generate the required folder structure and manually run the pipeline per SMRT cell._

how can I run the tool without LFS exactly for one SMRTcell?

Thanks for feedback

**Comment by DDDolle** [comment]
Hi,

Short answer:
--------------
* "Do we need to install IBM LSF to use your code?" -> No
* "Is this OK to install it on the SMRT-Link server?" -> I can't tell


Long answer:
-------------
The 'SEQUELstats.sh' script does use IBM Platform LSF but the actual pipeline scripts do not.
As the note in the 'README.md' states:

"While the SEQUELstats.sh script makes use of IBM Platform LSF Standard 9.1.3.0 for parallel processing of BAM files, the actual pipeline will run on any machine fulfilling the above-mentioned requirements. Hence, it is possible to generate the required folder structure and manually run the pipeline per SMRT cell."

'SEQUELstats.sh' is a control script for the pipeline. It's main task is to make processing of multiple SMRTcells per sample easy and fast by parallelizing it and by automatically generating the plots once ALL SMRTcells are processed. For this it loops through the individual steps (four in total) and for each step generates as many parallel jobs on the cluster as there are samples in the file-of-filenames (FOFNs). Each of theses jobs however runs on a single machine. So in theory you can use a simple script that uses two loops (one for the individual SMRTcells in the FOFNs and one that runs through the four pipeline steps) to do the job and run it on a single machine.

Imagine you have two FOFNs:

"subreads.fofn":
[
   a.sr.bam
   b.sr.bam
   c.sr.bam
]

"scraps.fofn":
[
   a.sc.bam
   b.sc.bam
   c.sc.bam
]

with "a", "b", and "c" being individual SMRTcells for the same sample. Further, the pipeline scripts and the FOFNs are all located in "/users/[user_name]/pipeline" and you want all output to end up in "/users/[user_name]/pipeline/output".

If you are in "/users/[user_name]/pipeline" The commands to run the whole pipeline on SMRTcell "a", "b", and "c" would then be:

(for "a")
./SEQUEL_pipe.sh ${PWD}/subreads.fofn ${PWD}/scraps.fofn ${PWD}/output 1 STEP_01
./SEQUEL_pipe.sh ${PWD}/subreads.fofn ${PWD}/scraps.fofn ${PWD}/output 1 STEP_02
./SEQUEL_pipe.sh ${PWD}/subreads.fofn ${PWD}/scraps.fofn ${PWD}/output 1 STEP_03
./SEQUEL_pipe.sh ${PWD}/subreads.fofn ${PWD}/scraps.fofn ${PWD}/output 1 STEP_04

(for "b")
./SEQUEL_pipe.sh ${PWD}/subreads.fofn ${PWD}/scraps.fofn ${PWD}/output 2 STEP_01
./SEQUEL_pipe.sh ${PWD}/subreads.fofn ${PWD}/scraps.fofn ${PWD}/output 2 STEP_02
./SEQUEL_pipe.sh ${PWD}/subreads.fofn ${PWD}/scraps.fofn ${PWD}/output 2 STEP_03
./SEQUEL_pipe.sh ${PWD}/subreads.fofn ${PWD}/scraps.fofn ${PWD}/output 2 STEP_04

(for "c")
./SEQUEL_pipe.sh ${PWD}/subreads.fofn ${PWD}/scraps.fofn ${PWD}/output 3 STEP_01
./SEQUEL_pipe.sh ${PWD}/subreads.fofn ${PWD}/scraps.fofn ${PWD}/output 3 STEP_02
./SEQUEL_pipe.sh ${PWD}/subreads.fofn ${PWD}/scraps.fofn ${PWD}/output 3 STEP_03
./SEQUEL_pipe.sh ${PWD}/subreads.fofn ${PWD}/scraps.fofn ${PWD}/output 3 STEP_04

You would however have to check manually after every step whether it finished successfully or produced an error. I had to build the scripts for our cluster so the automated solution is adapted for this and won't work on any other system. All it does however is checking whether the error log for each individual job contains an entry. If not it cleans up all the files that were only produced because it ran on a cluster. If you run it on a single node that you monitor yourself you won't need that.

The last thing 'SEQUELstats.sh' does is to copy the output files from the individual "Hn"/"HpSn"/"HpSp" folders per SMRTcell into one per type before running the plotting script on them (check the "PLOT" section in 'SEQUELstats.sh'). So it shouldn't be difficult for you to write a custom script that does that for you and you wouldn't need any other software than what's listed in the dependencies.

I hope this helps!


Best,

 Dirk

**Comment by splaisan** [comment]
Thanks a lot Dirk, I actually have only one pair of bam files now and will do as you described.
I keep you posted of the outcome here

**Comment by splaisan** [comment]
Here is how to run the tool for one pair of BAMS
I named it SEQUELstats4one.sh and it runs as is

**thanks to Dirk for the help**

I now 'only' need to understand how to interpret the plots ;-)

```
#!/bin/bash

# requirements:
# we work in a user writable folder
# scraps.fof in the current folder with the full path to the scraps.bam data
# subreads.fof in the current folder with the full path to the subreads.bam data
# $SEQUEL_STATS_path and other custom variables are defined as detailed in the README.md
# all dependencies are present

BASE=$(pwd)

# get sequel run-folder name from the scraps.fof
RUNNAME=$(cat scraps.fof)
RUNNAME=$(basename $RUNNAME)
RUNNAME=${RUNNAME%.scraps.bam}

# compute steps (check each succeeds before going on, STEP1 is the lengthiest as it parses the two BAMs
$SEQUEL_STATS_path/SEQUEL_pipe.sh subreads.fof scraps.fof $BASE 1 STEP_01
$SEQUEL_STATS_path/SEQUEL_pipe.sh subreads.fof scraps.fof $BASE 1 STEP_02
$SEQUEL_STATS_path/SEQUEL_pipe.sh subreads.fof scraps.fof $BASE 1 STEP_03
$SEQUEL_STATS_path/SEQUEL_pipe.sh subreads.fof scraps.fof $BASE 1 STEP_04

# the results should be in $BASE/${RUNNAME}/stats by now as 
# stats
#├── [4.0K]  Hn
#│   └── [ ]  ${RUNNAME}.Hn.stats
#├── [4.0K]  HpSn
#│   └── [ ]  ${RUNNAME}.HpSn.stats
#└── [4.0K]  HpSp
#    ├── [ ]  ${RUNNAME}.HpSp.aCnt
#    ├── [ ]  ${RUNNAME}.HpSp.hist
#    ├── [ ]  ${RUNNAME}.HpSp.lFlg
#    └── [ ]  ${RUNNAME}.HpSp.stats

# plot from resulting stats
Rscript $SEQUEL_STATS_path/SEQUEL_plot.R $BASE/${RUNNAME}/stats ${RUNNAME}_stats

# will create in stats:
# ${RUNNAME}_stats.estimated_lib_size_distribution.full_data.png
# ${RUNNAME}_stats.estimated_lib_size_distribution.png
# ${RUNNAME}_stats.Polymerase_and_subread.length_profiles.png
# ${RUNNAME}_stats.seq_run.yield_and_efficiency.png
# ${RUNNAME}_stats.SMRT_cell.efficiency.png
# ${RUNNAME}_stats.SMRT_cell.processed_output.png
# ${RUNNAME}_stats.SMRT_cell.raw_output.png

# done
```
